version: 0.2

phases:
  install:
    commands:
      # install node packages
      - npm i 
      # install lambda dependecy, may be do it using venv
      - pip install -r src/lambda/requirements.txt -t src/lambda/
      - zip -r src/lambda/demo_lambda.zip src/lambda/
  build:
    commands:
      - echo Build started on `date`
      - cdk synth
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    -