version: 0.2

phases:
  install:
    commands:
      # install node packages
      - npm i 
  build:
    commands:
      - bash scripts/deploy.sh
artifacts:
  files:
    - cdk.out
    - buildspec.yml
    - package.json